exports.rateLimiting = {
  requestsMinutesMax: 49,
  requestsMinutesCount: 0,
  requestsMinutesLast: 0,
  requestsDayMax: 999,
  requestsDayCount: 0,
  requestsDayLast: 0,
  requestsMinutesStartMax: 4,
  requestsMinutesStartCount: 0,
  requestsMinutesStartLast: 0,
  requestsMinutesStopMax: 4,
  requestsMinutesStopCount: 0,
  requestsMinutesStopLast: 0,
  responseErrorLast10MinutesMax: 9,
  responseErrorLast10MinutesCount: 0,
  responseErrorLast10MinutesLast: 0,
  requestBlock: false,
  requestBlockTime: 0,
  requestReason: 'No Block',
  requests: [],
};
exports.rateTokenLimiting = {
  tokenRefreshMinutesMax: 9,
  tokenRefreshMinutesCount: 0,
  tokenRefreshMinutesLast: 0,
  tokenRefreshDayMax: 99,
  tokenRefreshDayCount: 0,
  tokenRefreshDayLast: 0,
  tokenBlock: false,
  tokenBlockTime: 0,
  tokenReason: 'No Block',
};
